# Generated by Django 5.1.3 on 2025-08-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TODO',
            new_name='TODO_Table',
        ),
    ]
