# Generated by Django 5.1.3 on 2025-08-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_rename_todo_todo_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TODO_Table',
            new_name='ToDoTable',
        ),
    ]
