# Generated by Django 5.1.3 on 2025-08-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0003_rename_todo_table_todotable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotable',
            old_name='Task',
            new_name='Task_column',
        ),
    ]
